### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by joachimdoerr** [Suraj151/ckeditor5-embed#1]
Hello, 

this is a nice Plugin I like it, is it possible to integrate vimeo videos too?

Best Regards
Joachim

**Comment by Suraj151** [comment]
sorry for late reply.
actually i thought github will notify me, but its not...

yes...!!
it is possible. currently i have added only youtube support but we can make it better for others embed media too. just need to improve/allow logic at input link parser for other media.

you can try your logic of source parsing in **src/utils.js** file at **parseYtubeEmbed** function. i hope you can make and will notify once it work done.

**Comment by Suraj151** [comment]
added vimeo video embed support in new patch version..!
