### ISSUE TITLE
Ckeditor5 v11 compatibility

### ISSUE THREAD

**Issue by joachimdoerr** [Suraj151/ckeditor5-embed#2]
With the new ckeditor5 v11 we get problems with the dependency versions. In your current plugin the dependencies are to old. The result is that the editor will be display incorrectly.

Take a look at this issue: ckeditor/ckeditor5#1175

**Comment by Suraj151** [comment]
Ohh..!

thanks for update. i have not updated anything since last week.
will confirm and update the current changes in package.json.

**Comment by Suraj151** [comment]
updated
