### ISSUE TITLE
setData() strips off <iframe> tag

### ISSUE THREAD

**Issue by rivernews** [Suraj151/ckeditor5-embed#3]
Hi, first of all, nice work!

Two issues I'd like to report:

#### 1. setData() is stripping off <iframe>

Just came across when I use `ckeditor5-embed`, it perfectly inserted a YouTube video, and the `editor.getData()` works just fine, I can see the `<iframe>` is in the editor data.

However, when I tried to use `editor.setData( myPostContent )` to load post content in editor, Ckeditor seems to strip off `iframe`.

Interestingly, I found another repo that is also working on this iframe feature: https://github.com/akilli/ckeditor5-media ; I can not fully use it because it doesn't let you insert a piece of iframe string just as `ckeditor5-embed` does; nonetheless, it kind of let ckeditor recognize iframe and let`setData()` stop stripping off `iframe`. So I now can successfully do `setData` `getData` and the iframe content is showing correctly.

#### 2. Add iframe -> setData() -> put in more content -> setData(), things break

Together using `ckeditor5-embed` with `ckeditor5-media`, the following error is thrown after doing the sequence: ` Add iframe -> setData() -> put in more content -> setData()`

```

core.js:1598 ERROR TypeError: s.setAttribute is not a function
    at sa.<anonymous> (ckeditor.js:5)
    at sa.fire (ckeditor.js:5)
    at sa._convertItem (ckeditor.js:5)
    at sa._convertChildren (ckeditor.js:5)
    at sa.upcastDispatcher.on (ckeditor.js:5)
    at sa.fire (ckeditor.js:5)
    at sa._convertItem (ckeditor.js:5)
    at sa.convert (ckeditor.js:5)
    at model.change.n (ckeditor.js:5)
    at Gu.change (ckeditor.js:5)

```

Any ideas?

---

Lastly, I want to say that I kind of realize how hard it is to write a plugin for ckeditor5, so I really think you guys working on writing plugins are awesome! I tried like several days looking at the framework document, where it seems like they want you to understand how ckeditor5 is made from scratch before you can write a plugin. That said, using built-in plugin as example is good start, but their logic are still very complicated, I'll probably have to look at them for weeks.

**Comment by Suraj151** [comment]
ufff.... sorry, forgot to add upcast converter for embed.
will add and update..!! 

actually ckeditor5 needs to add upcast converter to convert view element to model element.

**Comment by Suraj151** [comment]
update: added upcast converter..!

update if any issue occurs again

thank you..!
